version: '3.8'

services:
  ludo-backend:
    image: ghcr.io/aybarci/ludogame/ludo-backend:latest
    container_name: ludo-backend
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0  # CRITICAL: Must be 0.0.0.0 for container communication
      - PORT=3001
      - DB_SERVER=mssql.istekbilisim.com
      - DB_DATABASE=LudoGameDB
      - DB_USER=sa
      - DB_PASSWORD=SeKo153759++
      - DB_PORT=1433
      - DB_ENCRYPT=false
      - DB_TRUST_SERVER_CERTIFICATE=true
      - JWT_SECRET=your-jwt-secret-key-here-change-this-in-production
      - REDIS_HOST=ludo-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - VATAN_SMS_API_ID=e922a5b11aae40dd84928621
      - VATAN_SMS_API_KEY=bcc4701b87c2490ea4bf1a80
      - VATAN_SMS_SENDER=Midpot
      - SMS_TEST_MODE=false
      - SMS_RATE_LIMIT_ENABLED=true
      - SMS_DAILY_LIMIT=1000
      - SMS_HOURLY_LIMIT=100
      - SMS_COOLDOWN_MS=60000
    volumes:
      - ./logs:/app/logs
    networks:
      - ludo-network
      - nginx-proxy-network  # Connect to reverse proxy network
      - web-network          # Connect to web services network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ludo-backend.rule=Host(`ludoturcoapi.istekbilisim.com`)"
      - "traefik.http.routers.ludo-backend.entrypoints=websecure"
      - "traefik.http.routers.ludo-backend.tls=true"
      - "traefik.http.services.ludo-backend.loadbalancer.server.port=3001"

  redis:
    image: redis:7-alpine
    container_name: ludo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ludo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ludo-network:
    driver: bridge
  nginx-proxy-network:
    external: true
    name: nginx-proxy-network
  web-network:
    external: true
    name: web-network

volumes:
  redis-data:
    driver: local