version: '3.8'

services:
  ludo-backend:
    image: ludo-backend:local
    container_name: ludo-backend
    restart: unless-stopped
    pull_policy: never
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_SERVER=mssql.istekbilisim.com
      - DB_DATABASE=ludoturcodb
      - DB_USER=sa
      - DB_PASSWORD=SeKo153759++
      - DB_PORT=1433
      - DB_ENCRYPT=false
      - DB_TRUST_SERVER_CERTIFICATE=true
      - JWT_SECRET=your-jwt-secret-key-here-change-this-in-production
      - REDIS_HOST=ludo-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - VATAN_SMS_API_ID=e922a5b11aae40dd84928621
      - VATAN_SMS_API_KEY=bcc4701b87c2490ea4bf1a80
      - VATAN_SMS_SENDER=Midpot
    volumes:
      - ./logs:/app/logs
    networks:
      - ludo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: ludo-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - ludo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ludo-network:
    driver: bridge

volumes:
  redis-data:
    driver: local