import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const loginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#6E00B3',
  },
  backgroundGradient: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  keyboardAvoidingView: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingTop: height * 0.05,
  },
  formContainer: {
    width: width * 0.9,
    maxWidth: 400,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 25,
    padding: 25,
    paddingBottom: 30,
    marginHorizontal: width * 0.05,
    marginBottom: height * 0.05,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  logoContainer: {
    marginBottom: 20,
    alignItems: 'center',
    shadowColor: '#00D9CC',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 10,
  },
  logoImage: {
    width: 200,
    height: 200,
    marginBottom: 5,
  },
  iconGlow: {
    position: 'absolute',
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 215, 0, 0.2)',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 8,
  },
  title: {
    fontSize: 42,
    fontWeight: 'bold',
    color: '#C8A842',
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 16,
    color: '#00D9CC',
    textAlign: 'center',
    marginBottom: 25,
    opacity: 0.9,
    fontWeight: '500',
  },
  inputsContainer: {
    marginBottom: 20,
  },
  inputWrapper: {
    marginBottom: 12,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 20,
    paddingHorizontal: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
    height: 55,
  },
  inputText: {
    color: 'white',
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
  },
  phoneInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(0, 217, 204, 0.3)',
    overflow: 'hidden',
  },
  countryCode: {
    paddingHorizontal: 15,
    paddingVertical: 15,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.2)',
  },
  countryCodeText: {
    color: '#00D9CC',
    fontSize: 16,
    fontFamily: 'Poppins_600SemiBold',
  },
  phoneInput: {
    flex: 1,
    color: 'white',
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
    paddingHorizontal: 15,
    paddingVertical: 15,
    // Placeholder styling için ek özellikler
    textAlignVertical: 'center', // Android için
    includeFontPadding: false, // Android için
    writingDirection: 'ltr', // Metin yönü
  },
  textInput: {
    flex: 1,
    color: 'white',
    fontSize: 16,
    fontFamily: 'Poppins_400Regular',
    paddingHorizontal: 20,
    paddingVertical: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    // Placeholder styling için ek özellikler
    textAlignVertical: 'center', // Android için
    includeFontPadding: false, // Android için
    writingDirection: 'ltr', // Metin yönü
  },
  buttonsContainer: {
    marginTop: 15,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
  },
  loadingText: {
    color: '#00D9CC',
    fontSize: 14,
    marginTop: 10,
    fontFamily: 'Poppins_500Medium',
  },
  primaryButton: {
    backgroundColor: '#E61A8D',
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#E61A8D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Poppins_600SemiBold',
    letterSpacing: 0.5,
  },
  switchButton: {
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 217, 204, 0.3)',
  },
  switchText: {
    color: '#00D9CC',
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
  },
  errorText: {
    color: '#ff6b6b',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: 'Poppins_500Medium',
  },
  successText: {
    color: '#4ecdc4',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 15,
    fontFamily: 'Poppins_500Medium',
  },
  linkText: {
    color: '#FFD700',
    textDecorationLine: 'underline',
    fontFamily: 'Poppins_500Medium',
  },
  footerText: {
    color: 'rgba(255, 255, 255, 0.7)',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 20,
    fontFamily: 'Poppins_400Regular',
  },
  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#2a2a3e',
    borderRadius: 20,
    padding: 25,
    width: width * 0.85,
    maxWidth: 350,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 215, 0, 0.3)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 15,
    textAlign: 'center',
    fontFamily: 'Poppins_600SemiBold',
  },
  modalText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
    fontFamily: 'Poppins_400Regular',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 15,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    fontFamily: 'Poppins_600SemiBold',
  },
  // Verification Modal specific styles
  verificationModal: {
    backgroundColor: '#1a1a2e',
    borderRadius: 25,
    padding: 30,
    width: width * 0.9,
    maxWidth: 400,
    alignItems: 'center',
    shadowColor: '#00D9CC',
    shadowOffset: { width: 0, height: 15 },
    shadowOpacity: 0.4,
    shadowRadius: 25,
    elevation: 25,
    borderWidth: 2,
    borderColor: 'rgba(0, 217, 204, 0.5)',
  },
  verificationTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#00D9CC',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'Poppins_700Bold',
    letterSpacing: 1,
  },
  verificationSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    marginBottom: 25,
    fontFamily: 'Poppins_400Regular',
  },
  codeInputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
    width: '100%',
  },
  codeInput: {
    width: 45,
    height: 55,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    textAlign: 'center',
    color: '#00D9CC',
    fontSize: 20,
    fontWeight: 'bold',
    fontFamily: 'Poppins_700Bold',
    borderWidth: 2,
    borderColor: 'rgba(0, 217, 204, 0.3)',
  },
  timerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  timerText: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.7)',
    marginLeft: 5,
    fontFamily: 'Poppins_400Regular',
  },
  resendButton: {
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 15,
  },
  resendButtonText: {
    color: '#00D9CC',
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
  },
  resendButtonDisabled: {
    opacity: 0.5,
  },
  verificationButton: {
    backgroundColor: '#6E00B3',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 25,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#6E00B3',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  verificationButtonText: {
    color: '#1a1a2e',
    fontSize: 16,
    fontWeight: 'bold',
    fontFamily: 'Poppins_600SemiBold',
  },
  verificationButtonDisabled: {
    backgroundColor: 'rgba(110, 0, 179, 0.3)',
    shadowOpacity: 0.2,
  },
  closeButton: {
    position: 'absolute',
    top: 15,
    right: 15,
    padding: 10,
  },
  closeButtonText: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 20,
    fontWeight: 'bold',
  },
  // Legal links (Privacy & Terms)
  legalContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  legalLink: {
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  legalLinkText: {
    color: '#00D9CC',
    fontSize: 13,
    fontFamily: 'Poppins_500Medium',
    textDecorationLine: 'underline',
    opacity: 0.9,
  },
  legalSeparator: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 14,
    fontFamily: 'Poppins_500Medium',
  },
});