// Basit emoji→Türkçe ad eşleme servisi
// Kapsamlı bir sözlük içerir; bulunamazsa emoji karakterini ad olarak döndürür.

const EMOJI_NAME_MAP = {
  // Yüz ifadeleri ve çeşitli emojiler
  '😀': 'Gülen Yüz',
  '😃': 'Güler Yüz',
  '😄': 'Kahkaha',
  '😁': 'Sırıtma',
  '😆': 'Kahkaha',
  '😅': 'Terli Gülme',
  '🤣': 'Kahkaha Krizi',
  '😂': 'Gülmekten Ağlama',
  '🙂': 'Nazik Gülümseme',
  '🙃': 'Ters Yüz',
  '😉': 'Göz Kırpma',
  '😊': 'Mutlu',
  '😇': 'Melek',
  '🥰': 'Aşık',
  '😍': 'Kalpli Göz',
  '🤩': 'Yıldız Göz',
  '😘': 'Öpücük',
  '😗': 'Öpücük',
  '☺️': 'Mahcup',
  '😚': 'Öpücük Göz Kapalı',
  '😙': 'Öpücük',
  '🥲': 'Gözyaşıyla Gülümseme',
  '😋': 'Yeme Keyfi',
  '😛': 'Dil Çıkarma',
  '😜': 'Şaşkın Dil',
  '🤪': 'Deli',
  '😝': 'Dil Çıkarıp Göz Kapalı',
  '🤑': 'Para Göz',
  '🤗': 'Sarılma',
  '🤭': 'Ağzı Kapalı',
  '🤫': 'Sessiz',
  '🤔': 'Düşünen',
  '🤐': 'Kilitli Ağız',
  '🤨': 'Kaş Kaldırma',
  '😐': 'Düz Yüz',
  '😑': 'İfadesiz',
  '😶': 'Ağızsız Yüz',
  '😏': 'Ukala',
  '😒': 'Memnuniyetsiz',
  '🙄': 'Göz Devirme',
  '😬': 'Sıkıntılı',
  '🤥': 'Yalancı',
  '😌': 'Rahatlamış',
  '😔': 'Üzgün',
  '😪': 'Uykulu',
  '🤤': 'Akan Salya',
  '😴': 'Uyuyan',
  '😷': 'Maske',
  '🤒': 'Hasta',
  '🤕': 'Yaralı',
  '🤢': 'Mide Bulantısı',
  '🤮': 'Kusma',
  '🤧': 'Nezle',
  '🥵': 'Sıcak',
  '🥶': 'Soğuk',
  '🥴': 'Sersem',
  '😵': 'Baş Dönmesi',
  '🤯': 'Patlayan Kafa',
  '🤠': 'Kovboy',
  '🥳': 'Parti',
  '🥸': 'Kılık Değiştir',
  '😎': 'Havalı',
  '🤓': 'Zeki',
  '🧐': 'Monokl',
  '😕': 'Kafası Karışık',
  '😟': 'Endişeli',
  '🙁': 'Somurtkan',
  '☹️': 'Somurtma',
  '😮': 'Ağzı Açık',
  '😯': 'Şaşırmış',
  '😲': 'Şok',
  '😳': 'Utanmış',
  '🥺': 'Yalvaran',
  '😦': 'Ağzı Açık Üzgün',
  '😧': 'Şaşkın Üzgün',
  '😨': 'Korkmuş',
  '😰': 'Endişeli Terli',
  '😥': 'Hüzünlü',
  '😢': 'Ağlayan',
  '😭': 'Hüngür Hüngür',
  '😱': 'Çığlık',
  '😖': 'Bunalmış',
  '😣': 'Yorgun',
  '😞': 'Hayal Kırıklığı',
  '😓': 'Terli Üzgün',
  '😩': 'Bıkmış',
  '😫': 'Bitkin',
  '🥱': 'Esneme',
  '😤': 'Öfkeli',
  '😡': 'Kızgın',
  '😠': 'Sinirli',
  '🤬': 'Sansürlü Öfke',
  '😈': 'Şeytani',
  '👿': 'Şeytan',
  '💀': 'Kafatası',
  '☠️': 'Kafatası ve Kemikler',
  '💩': 'Pasta (!) 💩',
  '🤡': 'Palyaço',
  '👹': 'Oni',
  '👺': 'Tengu',
  '👻': 'Hayalet',
  '👽': 'Uzaylı',
  '👾': 'Uzaylı Canavar',
  '🤖': 'Robot',
  '🎃': 'Bal Kabağı',
  '😺': 'Gülen Kedi',
  '😸': 'Güler Kedi',
  '😹': 'Gülen Kedi Ağlıyor',
  '😻': 'Kalpli Göz Kedi',
  '😼': 'Ukala Kedi',
  '😽': 'Öpücük Kedi',
  '🙀': 'Korkmuş Kedi',
  '😿': 'Ağlayan Kedi',
  '😾': 'Somurtkan Kedi',

  // Hayvanlar
  '🐱': 'Kedi',
  '🐶': 'Köpek',
  '🐭': 'Fare',
  '🐹': 'Hamster',
  '🐰': 'Tavşan',
  '🦊': 'Tilki',
  '🐻': 'Ayı',
  '🐼': 'Panda',
  '🐨': 'Koala',
  '🐯': 'Kaplan',
  '🦁': 'Aslan',
  '🐮': 'İnek',
  '🐷': 'Domuz',
  '🐽': 'Domuz Burnu',
  '🐸': 'Kurbağa',
  '🐵': 'Maymun',
  '🙈': 'Kötüyü Görme Maymunu',
  '🙉': 'Kötüyü Duyma Maymunu',
  '🙊': 'Kötüyü Söyleme Maymunu',
  '🐒': 'Maymun',
  '🐔': 'Tavuk',
  '🐧': 'Penguen',
  '🐦': 'Kuş',
  '🐤': 'Civciv',
  '🐣': 'Yumurtadan Çıkan Civciv',
  '🐥': 'Yüzü Öne Bakan Civciv',
  '🦆': 'Ördek',
  '🦅': 'Kartal',
  '🦉': 'Baykuş',
  '🦇': 'Yarasa',
  '🐺': 'Kurt',
  '🐗': 'Yaban Domuzu',
  '🐴': 'At',
  '🦄': 'Unicorn',
  '🐝': 'Arı',
  '🐛': 'Tırtıl',
  '🦋': 'Kelebek',
  '🐌': 'Salyangoz',
  '🐞': 'Uğur Böceği',
  '🐜': 'Karınca',
  '🦟': 'Sivrisinek',
  '🦗': 'Cırcır Böceği',
  '🕷️': 'Örümcek',
  '🕸️': 'Örümcek Ağı',
  '🦂': 'Akrep',
  '🐢': 'Kaplumbağa',
  '🐍': 'Yılan',
  '🦎': 'Kertenkele',
  '🦖': 'T-Rex',
  '🦕': 'Dinozor',
  '🐙': 'Ahtapot',
  '🦑': 'Kalamar',
  '🦐': 'Karides',
  '🦞': 'Istakoz',
  '🦀': 'Yengeç',
  '🐡': 'Kirpi Balığı',
  '🐠': 'Tropik Balık',
  '🐟': 'Balık',
  '🐬': 'Yunus',
  '🐳': 'Fışkırtan Balina',
  '🐋': 'Balina',
  '🦈': 'Köpekbalığı',
  '🐊': 'Timsah',
  '🐅': 'Kaplan',
  '🐆': 'Leopar',
  '🦓': 'Zebra',
  '🦍': 'Goril',
  '🦧': 'Orangutan',
  '🐘': 'Fil',
  '🦛': 'Su Aygırı',
  '🦏': 'Gergedan',
  '🐪': 'Tek Hörgüçlü Deve',
  '🐫': 'Çift Hörgüçlü Deve',
  '🦒': 'Zürafa',
  '🦘': 'Kanguru',
  '🐃': 'Manda',
  '🐂': 'Öküz',
  '🐄': 'İnek',
  '🐎': 'At',
  '🐖': 'Domuz',
  '🐏': 'Koç',
  '🐑': 'Koyun',
  '🦙': 'Lama',
  '🐐': 'Keçi',
  '🦌': 'Geyik',
  '🐕': 'Köpek',
  '🐩': 'Kaniş',
  '🦮': 'Rehber Köpek',
  '🐕‍🦺': 'Hizmet Köpeği',
  '🐈': 'Kedi',
  '🐈‍⬛': 'Siyah Kedi',
  '🐓': 'Horoz',
  '🦃': 'Hindi',
  '🦚': 'Tavuskuşu',
  '🦜': 'Papağan',
  '🦢': 'Kuğu',
  '🦩': 'Flamingo',
  '🕊️': 'Güvercin',
  '🐇': 'Tavşan',
  '🦝': 'Rakun',
  '🦨': 'Kokarca',
  '🦡': 'Porsuk',
  '🦦': 'Su Samuru',
  '🦥': 'Tembel Hayvan',
  '🐁': 'Fare',
  '🐀': 'Sıçan',
  '🐿️': 'Sincap',
  '🦔': 'Kirpi',
  '🐾': 'Pati İzi',

  // Doğa ve çevre
  '🌸': 'Kiraz Çiçeği',
  '🌺': 'Hibiskus',
  '🌻': 'Ayçiçeği',
  '🌷': 'Lale',
  '🌹': 'Gül',
  '🥀': 'Solmuş Gül',
  '🌾': 'Başak',
  '🌿': 'Yaprak',
  '🍀': 'Yonca',
  '🍃': 'Uçan Yaprak',
  '🍂': 'Düşen Yaprak',
  '🍁': 'Akçaağaç Yaprağı',
  '🌱': 'Fide',
  '🌲': 'Çam Ağacı',
  '🌳': 'Ağaç',
  '🌴': 'Palmiye',
  '🌵': 'Kaktüs',
  '🌶️': 'Biber',
  '🍄': 'Mantar',
  '🌰': 'Kestane',
  '🌟': 'Yıldız',
  '⭐': 'Yıldız',
  '🌠': 'Kayan Yıldız',
  '☀️': 'Güneş',
  '🌞': 'Güneş Yüz',
  '🌝': 'Dolunay Yüz',
  '🌛': 'Ay Dönence',
  '🌜': 'Hilal Yüz',
  '🌚': 'Yeni Ay Yüz',
  '🌕': 'Dolunay',
  '🌖': 'Şişkin Ay',
  '🌗': 'Yarım Ay',
  '🌘': 'Hilal Ay',
  '🌑': 'Yeni Ay',
  '🌒': 'Hilal',
  '🌓': 'İlk Dördün',
  '🌔': 'Büyüyen Ay',
  '🌙': 'Ay',
  '⚡': 'Şimşek',
  '⛈️': 'Gök Gürültülü Yağmur',
  '🌩️': 'Fırtına',
  '🔥': 'Ateş',
  '💥': 'Patlama',
  '❄️': 'Kar Tanesi',
  '🌨️': 'Kar Yağışı',
  '☃️': 'Kardan Adam',
  '⛄': 'Kardan Adam',
  '🌬️': 'Rüzgar',
  '💨': 'Hız Çizgisi',
  '🌪️': 'Hortum',
  '🌊': 'Dalga',
  '💧': 'Su Damlası',
  '💦': 'Su Şeritleri',
  '☔': 'Şemsiye Yağmur',
  '🌈': 'Gökkuşağı',
  '🌍': 'Dünya (Avrupa-Afrika)',
  '🌎': 'Dünya (Amerika)',
  '🌏': 'Dünya (Asya-Avustralya)',
  '🌐': 'Küresel',
  '🗺️': 'Harita',
  '🧭': 'Pusula',
  '🏔️': 'Dağ',
  '⛰️': 'Dağ',
  '🌋': 'Volkan',
  '🗻': 'Dağ',
  '🏕️': 'Kamp',
  '🏖️': 'Plaj',
  '🏜️': 'Çöl',
  '🏝️': 'Ada',
  '🏞️': 'Milli Park',
  '⛺': 'Çadır',
  '⛲': 'Çeşme',
  '🌁': 'Sis',
  '🌃': 'Gece',
  '🌄': 'Gün Doğumu',
  '🌅': 'Günbatımı',
  '🌆': 'Akşam',
  '🌇': 'Akşamüstü',
  '🌉': 'Köprü',
  '♨️': 'Kaplıca',
  '🎠': 'Atlıkarınca',
  '🎡': 'Dönme Dolap',
  '🎢': 'Roller Coaster',
  '💈': 'Berber Direği',

  // Araçlar ve ulaşım
  '🚗': 'Araba',
  '🚕': 'Taksi',
  '🚙': 'SUV',
  '🚌': 'Otobüs',
  '🚎': 'Trolleybus',
  '🏎️': 'Yarış Arabası',
  '🚓': 'Polis Aracı',
  '🚑': 'Ambulans',
  '🚒': 'İtfaiye',
  '🚐': 'Minibüs',
  '🛻': 'Pickup',
  '🚚': 'Kamyon',
  '🚛': 'Tır',
  '🚜': 'Traktör',
  '🏍️': 'Motosiklet',
  '🛵': 'Skuter',
  '🚲': 'Bisiklet',
  '🛴': 'Scooter',
  '🛺': 'Tuk-Tuk',
  '🚁': 'Helikopter',
  '🛸': 'UFO',
  '🚀': 'Roket',
  '✈️': 'Uçak',
  '🛩️': 'Küçük Uçak',
  '🛫': 'Uçak Kalkış',
  '🛬': 'Uçak İniş',
  '🪂': 'Paraşüt',
  '💺': 'Koltuk',
  '🚂': 'Lokomotif',
  '🚃': 'Demiryolu Vagonu',
  '🚄': 'Hızlı Tren',
  '🚅': 'Şinkansen',
  '🚆': 'Tren',
  '🚇': 'Metro',
  '🚈': 'Hafif Raylı',
  '🚉': 'Tren İstasyonu',
  '🚊': 'Tramvay',
  '🚝': 'Monoray',
  '🚞': 'Dağ Treni',
  '🚋': 'Tramvay Vagonu',
  '🚟': 'Asma Monoray',
  '🚠': 'Teleferik',
  '🚡': 'Kabinli Teleferik',
  '⛵': 'Yelkenli',
  '🛶': 'Kano',
  '🚤': 'Hız Teknesi',
  '🛥️': 'Motorlu Tekne',
  '🛳️': 'Kruvazör',
  '⛴️': 'Feribot',
  '🚢': 'Gemi',
  '⚓': 'Çapa',
  '⛽': 'Benzin İstasyonu',
  '🚧': 'Yol Çalışması',
  '🚨': 'Sireni',
  '🚥': 'Trafik Işığı (Yatay)',
  '🚦': 'Trafik Işığı (Dikey)',
  '🛑': 'Dur Tabelası',
  '🚏': 'Otobüs Durağı',
  '🛤️': 'Demiryolu',
  '🛣️': 'Otoyol',
  '🗺️': 'Harita',
  '🧭': 'Pusula',
  '🚘': 'Sedan',
  '🚖': 'Taksi',
  '🚔': 'Polis Aracı',
  '🚍': 'Otobüs'
};

export function getEmojiDisplayName(emoji) {
  // Eğer haritada varsa Türkçe adını döndür
  if (EMOJI_NAME_MAP[emoji]) return EMOJI_NAME_MAP[emoji];
  // Yoksa emoji karakterinin kendisini ad olarak göster (sayılardan kaçınmak için)
  return emoji || '';
}