# Traefik Configuration for Production
global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: api.your-domain.com
            sans:
              - www.api.your-domain.com
  
  traefik:
    address: ":8080"

certificatesResolvers:
  letsencrypt:
    acme:
      email: your-email@domain.com
      storage: acme.json
      keyType: EC256
      httpChallenge:
        entryPoint: web
  
  letsencrypt-dns:
    acme:
      email: your-email@domain.com
      storage: acme-dns.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare  # Change based on your DNS provider
        delayBeforeCheck: 0

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: ludo-production-network
    watch: true

# Middlewares
http:
  middlewares:
    # Security headers
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Frame-Options: "DENY"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"
          Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
        referrerPolicy: "no-referrer"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Rate limiting
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: 1m
        sourceCriterion:
          ipStrategy:
            depth: 1
    
    # Compression
    compression:
      compress: true
    
    # Circuit breaker
    circuit-breaker:
      circuitBreaker:
        expression: "NetworkErrorRatio() > 0.5"
        checkPeriod: 10s
        fallbackDuration: 30s
        recoveryDuration: 30s

# Metrics and monitoring
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# Logging
log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log

# Access logs
accessLog:
  format: json
  filePath: /var/log/traefik/access.log
  filters:
    statusCodes:
      - "200-299"
      - "400-599"
    retryAttempts: true
    minDuration: 10ms
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        Authorization: drop
        Cookie: drop
        Set-Cookie: drop

# Experimental features
experimental:
  plugins:
    enabled: true
    modules:
      - github.com/traefik/plugin-simplecache
      - github.com/traefik/plugin-rewritebody