version: '3.8'

services:
  ludo-web:
    image: ghcr.io/aybarci/ludogame/ludo-web:latest
    container_name: ludo-web
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3002:3000"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge