version: '3.8'

services:
  ludo-web:
    image: ghcr.io/aybarci/ludogame/ludo-web:latest
    container_name: ludo-web
    restart: unless-stopped
    pull_policy: always
    ports:
      - "3002:3000"
    networks:
      - web-network
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  web-network:
    driver: bridge